-- ----------------------------------------------------------------------
-- IDesign Moz — Proposal System
-- proposals: document generated by admin (services, discounts, tax, total)
-- status track: draft -> sent -> approved | rejected | changes_requested
-- Access is exclusively via the API (service role); RLS is enabled with no
-- anonymous policies so proposals stay private.
-- ----------------------------------------------------------------------

create table if not exists public.proposals (
  id                uuid primary key default gen_random_uuid(),
  code              text not null unique,              -- e.g. 'PRO-4F3A'
  token             text not null unique,              -- share token for /proposta/[token]
  title             text not null,
  client_name       text not null,
  client_email      text,
  client_company    text,
  services          jsonb not null default '[]',       -- [{key,label,detail,qty,unitPrice}]
  subtotal          integer not null default 0,        -- MT
  discount_percent  integer not null default 0,        -- percent
  discount_amount   integer not null default 0,        -- MT
  tax_rate          integer not null default 15,       -- percent
  tax_amount        integer not null default 0,        -- MT
  total             integer not null default 0,        -- MT
  validity_days     integer not null default 30,
  notes             text,
  status            text not null default 'draft'
                    check (status in ('draft', 'sent', 'approved', 'rejected', 'changes_requested')),
  client_comment    text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

alter table public.proposals enable row level security;

create or replace function public.touch_proposals()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists proposals_touch on public.proposals;
create trigger proposals_touch
  before update on public.proposals
  for each row execute procedure public.touch_proposals();

create index if not exists proposals_status_idx on public.proposals (status);